### ISSUE TITLE
 Installing the sirirus 4.4 Gui version

### ISSUE THREAD

**Issue by YonghuiDong** [boecker-lab/sirius#7] opened 2020-06-01 09:23 UTC
Hi SIRIRUS 4 developers,

I am having troubles in installing the sirirus 4.4 Gui version. The following errors pop up. Could you help to inspect the problem?

Thanks a lot.

Dong

Unexpected error!
org.openscience.cdk.exception.CDKException: Unable to load native code; net.sf.jnati.deploy.resolver.ArtefactNotFoundException: Artefact not found: jniinchi-1.03_1-WINDOWS-AMD64
	at org.openscience.cdk.inchi.InChIGeneratorFactory.<init>(InChIGeneratorFactory.java:87)
	at org.openscience.cdk.inchi.InChIGeneratorFactory.getInstance(InChIGeneratorFactory.java:102)
	at de.unijena.bioinf.ms.frontend.subtools.gui.GuiAppOptions$Flow$2.compute(GuiAppOptions.java:115)
	at de.unijena.bioinf.ms.frontend.subtools.gui.GuiAppOptions$Flow$2.compute(GuiAppOptions.java:106)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:95)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: net.sf.jniinchi.LoadNativeLibraryException: net.sf.jnati.deploy.resolver.ArtefactNotFoundException: Artefact not found: jniinchi-1.03_1-WINDOWS-AMD64
	at net.sf.jniinchi.JniInchiWrapper.loadLibrary(JniInchiWrapper.java:98)
	at org.openscience.cdk.inchi.InChIGeneratorFactory.<init>(InChIGeneratorFactory.java:85)
	... 8 more
Caused by: net.sf.jnati.deploy.resolver.ArtefactNotFoundException: Artefact not found: jniinchi-1.03_1-WINDOWS-AMD64
	at net.sf.jnati.deploy.NativeArtefactLocator.getArtefact(NativeArtefactLocator.java:80)
	at net.sf.jnati.deploy.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:47)
	at net.sf.jnati.deploy.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:41)
	at net.sf.jnati.deploy.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:37)
	at net.sf.jniinchi.JniInchiWrapper.loadLibrary(JniInchiWrapper.java:84)
	... 9 more

**Comment by mfleisch** [comment] 2020-06-01 09:36
Dear Yonghui Dong,
thanks for report. This is caused by som packaging problem. We are working on it and it will be fixed soon when we upload the build.

Best
Markus

**Comment by mfleisch** [comment] 2020-06-01 22:43
I could not exactly reproduce this issue but the chances are not too bad that build 4.4.25 will fix it.
Let me know If you still observe this issue.

**Closed by mfleisch** 2020-06-01 22:43 UTC
Labels: bug, doing
