### ISSUE TITLE
Sirius got troubles!

### ISSUE THREAD

**Issue by marcodaino** [boecker-lab/sirius#156] opened 2024-05-09 14:16 UTC
I have troubles computing my data since yesterday. On May 7th I did some computations (with the same .mgf file) and everything was fine.
Everything with my account ([marco.dainelli@unifi.it](mailto:marco.dainelli@unifi.it)) seems ok. Webservice connection is ok.
I import my data and try to compute one feature, but the process stops at "CSI:FingerID - Fingerprint prediction" whit this message (repeated through time): 

"WARNING: Request to Server failed! Try again in 4.0s | Exception: de.unijena.bioinf.rest.SiriusHttpException | Cause: Http Request Failed in client `POOL_CLIENT`. Cause: `HttpErrorResponseException` | Message: `Error when querying REST service. Bad HTTP Response Code: 403 | HTTP-Message:  | HTTP-Request: GET: [https://www.csi-fingerid.uni-jena.de/v2.6/api/fingerid/data?predictor=1`](https://www.csi-fingerid.uni-jena.de/v2.6/api/fingerid/data?predictor=1)"

Can you please solve this problem?

**Comment by mfleisch** [comment] 2024-05-09 20:34
Duplicate of #155

**Closed by mfleisch** 2024-05-09 20:34 UTC
