### ISSUE TITLE
Hello! I have some troubles using Sirius

### ISSUE THREAD

**Issue by llbbhh112233** [boecker-lab/sirius#21] opened 2020-12-17 08:30 UTC
![image](https://user-images.githubusercontent.com/35490736/102462013-3e4c9880-4084-11eb-96f6-3a6fccb4e39d.png)
![image](https://user-images.githubusercontent.com/35490736/102462117-57554980-4084-11eb-8e93-9ebb15d94cdb.png)

Hello! 
When using "Sirius", I got the warning message below.  How can I solve this problem.
 
Connection error
org.apache.http.conn.ConnectTimeoutException: Connect to www.google.com:443 [www.google.com/157.240.3.50] failed: connect timed out
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:143)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at de.unijena.bioinf.webapi.ProxyManager$LockedClosableHttpClient.execute(ProxyManager.java:344)
	at de.unijena.bioinf.webapi.ProxyManager$LockedClosableHttpClient.execute(ProxyManager.java:313)
	at de.unijena.bioinf.webapi.ProxyManager.checkConnectionToUrl(ProxyManager.java:224)
	at de.unijena.bioinf.webapi.ProxyManager.checkExternal(ProxyManager.java:211)
	at de.unijena.bioinf.webapi.ProxyManager.checkInternetConnection(ProxyManager.java:135)
	at de.unijena.bioinf.webapi.WebAPI.lambda$checkConnection$0(WebAPI.java:134)
	at de.unijena.bioinf.webapi.ProxyManager.doWithClient(ProxyManager.java:279)
	at de.unijena.bioinf.webapi.WebAPI.checkConnection(WebAPI.java:130)
	at de.unijena.bioinf.ms.gui.net.ConnectionMonitor$CheckJob.compute(ConnectionMonitor.java:121)
	at de.unijena.bioinf.ms.gui.net.ConnectionMonitor$CheckJob.compute(ConnectionMonitor.java:117)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:95)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:337)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	... 24 more

Dec 17, 2020 4:19:25 PM de.unijena.bioinf.ms.rest.client.info.InfoClient getVersionInfo
警告: Could not reach fingerid version specific URL for version verification. Try to reach root url. Cause:Connect to www.csi-fingerid.uni-jena.de:443 [www.csi-fingerid.uni-jena.de/141.35.12.31] failed: Read timed out
Dec 17, 2020 4:19:25 PM de.unijena.bioinf.ms.rest.client.info.InfoClient getVersionInfo
警告: Could not reach fingerid version specific URL for version verification. Try to reach root url. Cause:Connect to www.csi-fingerid.uni-jena.de:443 [www.csi-fingerid.uni-jena.de/141.35.12.31] failed: Read timed out
Dec 17, 2020 4:19:57 PM de.unijena.bioinf.ms.rest.client.info.InfoClient getVersionInfo
警告: Could not reach fingerid version specific URL for version verification. Try to reach root url. Cause:Read timed out
Dec 17, 2020 4:19:57 PM de.unijena.bioinf.ms.rest.client.info.InfoClient getVersionInfo
警告: Could not reach fingerid version specific URL for version verification. Try to reach root url. Cause:Read timed out

**Comment by mfleisch** [comment] 2020-12-17 11:15
Hey,
is this issue reproducible/persistent? The most likely reason for this problem is that your internet connection was temporarily unavailable.

**Comment by llbbhh112233** [comment] 2020-12-17 12:11
Alright. But I still get into trouble when using sirius in linux. The error message is shown below:
SEVERE20:03:44 - Unexpected Error!
picocli.CommandLine$PicocliException: Could not initialize workspace!
	at de.unijena.bioinf.ms.frontend.subtools.CLIRootOptions.configureProjectSpace(CLIRootOptions.java:190)
	at de.unijena.bioinf.ms.frontend.subtools.CLIRootOptions.getProjectSpace(CLIRootOptions.java:135)
	at de.unijena.bioinf.ms.frontend.subtools.lcms_align.LcmsAlignSubToolJob.<init&gt;(LcmsAlignSubToolJob.java:60)
	at de.unijena.bioinf.ms.frontend.subtools.lcms_align.LcmsAlignOptions.makePreprocessingJob(LcmsAlignOptions.java:33)
	at de.unijena.bioinf.ms.frontend.subtools.lcms_align.LcmsAlignOptions.makePreprocessingJob(LcmsAlignOptions.java:28)
	at de.unijena.bioinf.ms.frontend.workflow.WorkflowBuilder$ParseResultHandler.handle(WorkflowBuilder.java:208)
	at de.unijena.bioinf.ms.frontend.workflow.WorkflowBuilder$ParseResultHandler.handle(WorkflowBuilder.java:188)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:2073)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:2454)
	at picocli.CommandLine.parseWithHandler(CommandLine.java:2389)
	at de.unijena.bioinf.ms.frontend.Run.parseArgs(Run.java:75)
	at de.unijena.bioinf.ms.frontend.SiriusCLIApplication.run(SiriusCLIApplication.java:106)
	at de.unijena.bioinf.ms.frontend.SiriusGUIApplication$1.compute(SiriusGUIApplication.java:84)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:95)
	at de.unijena.bioinf.ms.frontend.SiriusGUIApplication.main(SiriusGUIApplication.java:98)
Caused by: java.io.IOException: Location 'sirius_rosmarin' is not a valid Project Location
	at de.unijena.bioinf.projectspace.ProjectSpaceIO.openExistingProjectSpace(ProjectSpaceIO.java:56)
	at de.unijena.bioinf.ms.frontend.subtools.CLIRootOptions.configureProjectSpace(CLIRootOptions.java:156)
	... 14 more



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "boecker-lab/sirius"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月17日(星期四) 晚上7:16
收件人:&nbsp;"boecker-lab/sirius"<sirius@noreply.github.com&gt;;
抄送:&nbsp;"宅の魂"<462398474@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [boecker-lab/sirius] Hello! I have some troubles using Sirius (#21)





 
Hey,
 is this issue reproducible/persistent? The most likely reason for this problem is that your internet connection was temporarily unavailable.

**Comment by mfleisch** [comment] 2020-12-17 13:22
Please have a look at this issue:  https://github.com/boecker-lab/sirius/issues/17#issuecomment-733730430

**Comment by llbbhh112233** [comment] 2020-12-18 06:55
Thanks, but I still have some troubles when using "LC-MS align". I got the messages below:
&nbsp;sirius -i mzml&nbsp; -o ./result_2 lcms-align formula
INFO&nbsp; 14:38:10 - Sirius Workspace Successfull initialized at: /home/lbh/.sirius-4.5
INFO&nbsp; 14:38:10 - You run SIRIUS 4.5.1
INFO&nbsp; 14:38:10 - Sirius was compiled with the following ILP solvers: GLPK-v1.7.0 (included), Gurobi-v8.1.0, CPLEX-v12.7.1, COIN-OR-v1.17.3
INFO&nbsp; 14:38:10 - Treebuilder priorities are: [CLP, CPLEX, GUROBI, GLPK]
INFO&nbsp; 14:38:11 - CPU check done. 60 cores that handle 120 threads were found.
INFO&nbsp; 14:38:11 - Bug reporter initialized.
INFO&nbsp; 14:38:11 - Web API initialized.
INFO&nbsp; 14:38:11 - Running with following arguments: [-i, mzml, -o, ./result_2, lcms-align, formula]
INFO&nbsp; 14:38:11 - Job manager successful initialized with 60 CPU thread(s) and 3 IO thread(s).
FINE&nbsp; 14:38:11 - InputExpanderJJob (0): Running post processing
FINE&nbsp; 14:38:11 - InputExpanderJJob (0): Running cleanup
INFO&nbsp; 14:38:11 - InputExpanderJJob (1): Expanding Input Files: 'mzml'...
INFO&nbsp; 14:38:11 - InputExpanderJJob (1): ...Input Files successfully expanded!
FINE&nbsp; 14:38:11 - InputExpanderJJob (1): Running post processing
FINE&nbsp; 14:38:11 - InputExpanderJJob (1): Running cleanup
WARNING14:38:13 - MzIdentML Configuration file: jar:file:/home/lbh/sirius/test/sirius/lib/app/jmzml-1.7.11.jar!/defaultMzMLElement.cfg.xml
INFO&nbsp; 14:39:32 - Number of scans outside = 0, number of scans inside = 0, number of multiplies = 0
INFO&nbsp; 14:39:33 - Number of scans outside = 0, number of scans inside = 2, number of multiplies = 0
WARNING14:39:34 - MS2 scan outside of an segment of an chromatographic peak
INFO&nbsp; 14:39:34 - Number of scans outside = 1, number of scans inside = 1, number of multiplies = 0
INFO&nbsp; 14:39:35 - Number of scans outside = 0, number of scans inside = 0, number of multiplies = 0
INFO&nbsp; 14:39:36 - Number of scans outside = 0, number of scans inside = 2, number of multiplies = 0
INFO&nbsp; 14:39:38 - Number of scans outside = 0, number of scans inside = 0, number of multiplies = 0
INFO&nbsp; 14:40:38 - Number of scans outside = 0, number of scans inside = 2, number of multiplies = 0
INFO&nbsp; 14:40:38 - Number of scans outside = 0, number of scans inside = 0, number of multiplies = 0
INFO&nbsp; 14:40:41 - Number of scans outside = 0, number of scans inside = 0, number of multiplies = 0
WARNING14:40:44 - MS2 scan outside of an segment of an chromatographic peak
INFO&nbsp; 14:40:44 - Number of scans outside = 0, number of scans inside = 2, number of multiplies = 0
INFO&nbsp; 14:40:44 - Number of scans outside = 1, number of scans inside = 1, number of multiplies = 0
INFO&nbsp; 14:40:47 - Number of scans outside = 0, number of scans inside = 1, number of multiplies = 0
INFO&nbsp; 14:40:49 - Number of scans outside = 0, number of scans inside = 4, number of multiplies = 0
INFO&nbsp; 14:40:54 - Number of scans outside = 0, number of scans inside = 0, number of multiplies = 0
ERROR = 10000.0
Start with 9 unaligned ions.
Remove features with low MS/MS quality that do not align properly
Remove 9 features that do not align well. Keep 0 features.
USED 0 features for error estimation. Mean error is NaN
Not enough aligned features to recalibrate file:/home/lbh/test/raw_file/pos/mzml/cent_new_POS-0506-T-07.mzML
Not enough aligned features to recalibrate file:/home/lbh/test/raw_file/pos/mzml/cent_new_POS-0506-T-06.mzML
Not enough aligned features to recalibrate file:/home/lbh/test/raw_file/pos/mzml/cent_new_POS-0506-T-101.mzML
Not enough aligned features to recalibrate file:/home/lbh/test/raw_file/pos/mzml/cent_new_POS-0506-T-09.mzML
Not enough aligned features to recalibrate file:/home/lbh/test/raw_file/pos/mzml/cent_new_POS-0506-T-100.mzML
Not enough aligned features to recalibrate file:/home/lbh/test/raw_file/pos/mzml/cent_new_POS-0506-T-08.mzML
Not enough aligned features to recalibrate file:/home/lbh/test/raw_file/pos/mzml/cent_new_POS-0506-T-105.mzML
Not enough aligned features to recalibrate file:/home/lbh/test/raw_file/pos/mzml/cent_new_POS-0506-T-106.mzML
Not enough aligned features to recalibrate file:/home/lbh/test/raw_file/pos/mzml/cent_new_POS-0506-T-107.mzML
Not enough aligned features to recalibrate file:/home/lbh/test/raw_file/pos/mzml/cent_new_POS-0506-T-109.mzML
Not enough aligned features to recalibrate file:/home/lbh/test/raw_file/pos/mzml/cent_new_POS-0506-T-108.mzML
Not enough aligned features to recalibrate file:/home/lbh/test/raw_file/pos/mzml/cent_new_POS-0506-T-103.mzML
Not enough aligned features to recalibrate file:/home/lbh/test/raw_file/pos/mzml/cent_new_POS-0506-T-102.mzML
Not enough aligned features to recalibrate file:/home/lbh/test/raw_file/pos/mzml/cent_new_POS-0506-T-104.mzML
USED 0 features for error estimation. Mean error is NaN
Start Gapfilling #2
USED 0 features for error estimation. Mean error is NaN
########################################
Initial Error: 10000.0
After clustering: NaN
After Recalibration: NaN
After Gap-Filling: NaN
PeakShape Error: NaN
Remove NaN % of the data due to low quality. There are 0 features in total.
Done.
Total number of features is 0
INFO&nbsp; 14:40:55 - Workflow has been finished!
INFO&nbsp; 14:40:55 - Executing Postprocessing...
INFO&nbsp; 14:40:56 - Writing summary files...
INFO&nbsp; 14:40:56 - Project-Space summaries successfully written!
INFO&nbsp; 14:40:56 - CLI shut down hook: SIRIUS is cleaning up threads and shuts down...




Please cite the following publications when using our tool:


When using the SIRIUS Software please cite the following paper:


Kai Dührkop, Markus Fleischauer, Marcus Ludwig, Alexander A. Aksenov, Alexey V. Melnik, Marvin Meusel, Pieter C. Dorrestein, Juho Rousu and Sebastian Böcker
SIRIUS4: a rapid tool for turning tandem mass spectra into metabolite structure information
Nat Methods, 16, 2019.&nbsp; https://doi.org/10.1038/s41592-019-0344-8




Depending on the tools you have used please also cite:


Kai Dührkop, Louis-Félix Nothias, Markus Fleischauer, Raphael Reher, Marcus Ludwig, Martin A. Hoffmann, Daniel Petras, William H. Gerwick, Juho Rousu, Pieter C. Dorrestein and Sebastian Böcker
Systematic classification of unknown metabolites using high-resolution fragmentation mass spectra
Nature Biotechnology, 2020.&nbsp; https://doi.org/10.1038/s41587-020-0740-8
(Cite if you are using: CANOPUS)


Yannick Djoumbou Feunang, Roman Eisner, Craig Knox, Leonid Chepelev, Janna Hastings, Gareth Owen, Eoin Fahy, Christoph Steinbeck, Shankar Subramanian, Evan Bolton, Russell Greiner, David S. Wishart
ClassyFire: automated chemical classification with a comprehensive, computable taxonomy
J Cheminf, 8, 2016.&nbsp; https://doi.org/10.1186/s13321-016-0174-y
(Cite if you are using: CANOPUS)


Kai Dührkop, Huibin Shen, Marvin Meusel, Juho Rousu and Sebastian Böcker
Searching molecular structure databases with tandem mass spectra using CSI:FingerID
Proc Natl Acad Sci U S A, 112, 2015.&nbsp; https://doi.org/10.1073/pnas.1509788112
(Cite if you are using: CSI:FingerID)


Sebastian Böcker and Kai Dührkop
Fragmentation trees reloaded
J Cheminform, 8, 2016.&nbsp; https://doi.org/10.1186/s13321-016-0116-8
(Cite if you are using: Fragmentation Trees)


Sebastian Böcker, Matthias Letzel, Zsuzsanna Lipták and Anton Pervukhin
SIRIUS: Decomposing isotope patterns for metabolite identification
Bioinformatics, 25, 2009.&nbsp; https://doi.org/10.1093/bioinformatics/btn603
(Cite if you are using: Isotope Pattern analysis)


Marcus Ludwig, Louis-Félix Nothias, Kai Dührkop, Irina Koester, Markus Fleischauer, Martin A. Hoffmann, Daniel Petras, Fernando Vargas, Mustafa Morsy, Lihini Aluwihare, Pieter C. Dorrestein, Sebastian Böcker
ZODIAC: database-independent molecular formula annotation using Gibbs sampling reveals unknown small molecules
bioRxiv, 2019.&nbsp; https://doi.org/10.1101/842740
(Cite if you are using: ZODIAC)


The picture below is my data opened by mzmine














------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Markus Fleischauer"<notifications@github.com&gt;; 
发送时间: 2020年12月17日(星期四) 晚上9:23
收件人: "boecker-lab/sirius"<sirius@noreply.github.com&gt;; 
抄送: "宅の魂"<462398474@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [boecker-lab/sirius] Hello! I have some troubles using Sirius (#21)





 
Please have a look at this issue:  #17 (comment)

**Comment by kaibioinfo** [comment] 2020-12-18 11:13
Your mzml files seem to contain only very few MS/MS spectra (around 10). I think there is no meaning in aligning ten features. If you just want to extract the MS/MS run the tool without the lcms-align subtool.

**Comment by llbbhh112233** [comment] 2020-12-18 13:33
Thanks!&nbsp; I'm really appreciate your help!&nbsp; But my mzml file has more than 10 MS/MS spectra, I still confused. I have uploaded my mzml file and additionally I found my internet connection was not stable, it will take a very long time to get the canopus result, do you have any solutions?
Best regards!
Bohai Li




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "boecker-lab/sirius"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月18日(星期五) 晚上7:13
收件人:&nbsp;"boecker-lab/sirius"<sirius@noreply.github.com&gt;;
抄送:&nbsp;"宅の魂"<462398474@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [boecker-lab/sirius] Hello! I have some troubles using Sirius (#21)





 
Your mzml files seem to contain only very few MS/MS spectra (around 10). I think there is no meaning in aligning ten features. If you just want to extract the MS/MS run the tool without the lcms-align subtool.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

cent_new_POS-0506-T-102.mzML (190.88M, 2021年01月17日 21:17 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=666436318cd627cc3dc0b92a43350417035101555750060c1a0200075418020052511b5300025315070500025106025b530655546529365b520a426e0b504167672b651c5500060e1a301b00550718554d297a3158&code=7d61e568

**Comment by kaibioinfo** [comment] 2020-12-18 23:57
Hi,

I checked your mzml file and it seems that you have DIA data. We do not support this kind of data: mass spectra in DIA are highly multiplexed and have to be deconvoluted first. You can try MSFinder which is one of the few software methods that can deal with such kind of data.

**Comment by llbbhh112233** [comment] 2020-12-21 00:42
Thanks, but I'm very interested in CANOPUS and want to predict compound class of differential metabolites. I run&nbsp; "sirius -i&nbsp; XX.mgf -o&nbsp;&nbsp;formula -c 10 structure --database pubchem canopus" to my mgf data. However , It has run for four days and I didn't find the "canopus_summary.tsv" file in the result directory. Some of files in result directory has "canopus"&nbsp; and "canopus_npc" ,but some files don't have. Is that normal?






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "boecker-lab/sirius"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月19日(星期六) 上午7:58
收件人:&nbsp;"boecker-lab/sirius"<sirius@noreply.github.com&gt;;
抄送:&nbsp;"宅の魂"<462398474@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [boecker-lab/sirius] Hello! I have some troubles using Sirius (#21)





 
Hi,
 
I checked your mzml file and it seems that you have DIA data. We do not support this kind of data: mass spectra in DIA are highly multiplexed and have to be deconvoluted first. You can try MSFinder which is one of the few software methods that can deal with such kind of data.

**Comment by mfleisch** [comment] 2021-01-20 14:14
SIRIUS writes results to disk as soon as they are available but summary files are written as very last step of a analysis. 
So if the analysis was stopped forcefully or crashed it is likely that summary files have not been written.

However summaries can be created from an existing project separately by reading the project-space without doing anything.

```shell
sirius -i <my-project> project-space
```

**Comment by mfleisch** [comment] 2021-01-20 14:16
I am closing this issue because it is not focused on a specific topic.
If there are further issues please open a new issue (per topic) with a descriptive title.

**Closed by mfleisch** 2021-01-20 14:16 UTC
